'use client'
import { Inter,Albert_Sans } from 'next/font/google'
import Sidebar from '@/components/Sidebar'
import { ThemeContextProvider } from './Context/theme'
import { useThemeContext } from './Context/theme'
import { usePathname } from 'next/navigation'

import './globals.css'
import Login_com from '@/components/Login_com'


const albert_sans = Albert_Sans({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  const pathname = usePathname()
    
  return (
    <html lang="en">
      <body className={`${albert_sans.className}  w-full h-[982px] bg-[#F6F6FB]`}>
      
      <ThemeContextProvider>
      
      <div className={`flex ${pathname !== '/login' ? 'p-4' : 'p-0'}`}>
      <div className=''>
      {pathname !== '/login' && <Sidebar/>}
      </div>
      {/* <div>other</div> */}
      
    <div className={`w-full ${pathname !== '/login' ? 'pl-4' : 'pl-0'}`}>
        {children}
    </div>
      
      </div>
      </ThemeContextProvider>
      </body>
    </html>
  )
}
